import { TaskEntry, ProjectInfo } from './types';

// Let's generate a list of initial projects
export const INITIAL_PROJECTS: ProjectInfo[] = [
  {
    name: 'Siemens WinCC SCADA Upgrade',
    status: 'On Track',
    leadEngineer: 'Balarathu',
    description: 'Upgrading central control room to WinCC V18 running on modern IPCs.',
    assignedEngineers: ['Balarathu'],
  },
  {
    name: 'Line 3 Palletizer Automation',
    status: 'On Track',
    leadEngineer: 'Balarathu',
    description: 'Integrating S7-1500 Controller with Profinet and safety interlocks.',
    assignedEngineers: ['Balarathu', 'Sarah Thompson'],
  },
  {
    name: 'Water Treatment Plant Telemetry',
    status: 'Completed',
    leadEngineer: 'Sarah Thompson',
    description: 'Setting up remote RTUs and cellular telemetry with MQTT.',
    assignedEngineers: ['Sarah Thompson', 'Markus V'],
  },
];

// Current date in year 2026-06-02
export const INITIAL_TASKS: TaskEntry[] = [
  {
    id: 't1',
    date: '2026-06-01',
    project: 'Siemens WinCC SCADA Upgrade',
    category: 'PROJECT_TRACK',
    description: 'Successfully configured OPC UA communication channels and tested Tag logging.',
    status: 'In Progress',
    timeSpent: 4,
    engineer: 'Balarathu',
  },
  {
    id: 't2',
    date: '2026-06-01',
    project: 'Office Work',
    category: 'LICENSE_TRANSFER',
    description: 'Processed 3 Siemens license transfers for client WinCC RT licenses. Answered service request #SR-99812.',
    status: 'Completed',
    timeSpent: 1.5,
    completedDate: '2026-06-01',
    engineer: 'Markus V',
  },
  {
    id: 't3',
    date: '2026-06-01',
    project: 'Line 3 Palletizer Automation',
    category: 'SALES_SUPPORT',
    description: 'Replied to Sales Engineer\'s configuration request for Line 3 expansion quote with complete bill of materials.',
    status: 'Completed',
    timeSpent: 2,
    completedDate: '2026-06-01',
    engineer: 'Sarah Thompson',
  },
  {
    id: 't4',
    date: '2026-06-02',
    project: 'Line 3 Palletizer Automation',
    category: 'PROJECT_TRACK',
    description: 'Commissioned safety relay monitoring and mapped alarms to HMI screens.',
    status: 'In Progress',
    timeSpent: 3.5,
    engineer: 'Balarathu',
  },
  {
    id: 't5',
    date: '2026-06-02',
    project: 'Office Work',
    category: 'ONLINE_SUPPORT',
    description: 'Facilitated online support session via TeamViewer to debug network mismatch on Siemens S7 ET200sp remote station.',
    status: 'Completed',
    timeSpent: 2.5,
    completedDate: '2026-06-02',
    engineer: 'Markus V',
  },
  {
    id: 't6',
    date: '2026-06-02',
    project: 'General Support',
    category: 'CUSTOMER_EMAIL',
    description: 'Replied to 5 customer support emails regarding license upgrades and network requirements.',
    status: 'Completed',
    timeSpent: 1.5,
    completedDate: '2026-06-02',
    engineer: 'Sarah Thompson',
  },
  {
    id: 't7',
    date: '2026-05-30',
    project: 'Water Treatment Plant Telemetry',
    category: 'PROJECT_TRACK',
    description: 'Final loop checks and site acceptance test (SAT) for remote RTU panel.',
    status: 'Completed',
    timeSpent: 8,
    completedDate: '2026-05-30',
    engineer: 'Sarah Thompson',
  },
  {
    id: 't8',
    date: '2026-05-29',
    project: 'Line 3 Palletizer Automation',
    category: 'LICENSE_TRANSFER',
    description: 'Managed Siemens Automation License Manager (ALM) transfer of Step 7 Professional v18 licenses for field laptops.',
    status: 'Completed',
    timeSpent: 1.2,
    completedDate: '2026-05-29',
    engineer: 'Sarah Thompson',
  },
];
